# Project language
language: php

dist: bionic

# php version
php:
  - '8.3'

# Allows use container-based infrastructure
sudo: false

# Start mysql service
services:
  - mysql

# Define an environment variable
env:
  - SYMFONY_VERSION="5.4.*" DB=mysql

test:
  adapter: mysql2
  username: root
  password: root
  encoding: utf8

# Update composer
before-install:
  - composer self-update
  - composer install --prefer-source --no-interaction

# Install composer dependencies,
# Create database, schema and fixtures
install:
  - composer install --prefer-dist --no-interaction
  - php bin/console doctrine:database:create --env.local=test
  - php bin/console doctrine:schema:update --force --env.local=test
  - php bin/console doctrine:fixtures:load -n --env.local=test

# Run script
script:
  - composer install
  - vendor/bin/phpunit

#branches:
#  only:
#    - units_tests